LoginExperiments/Models/MfaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LoginExperiments.Models
{
	public class MfaViewModel
	{
		public string TotpKey { get; set; }

		public string RecoveryKey { get; set; }
	}
}

LoginExperiments/Controllers/MfaController.cs
using Fido2NetLib;
using Fido2NetLib.Objects;
using LoginExperiments.Database;
using LoginExperiments.Extensions;
using LoginExperiments.Models;
using LoginExperiments.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OtpNet;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LoginExperiments.Controllers
{
	[Authorize]
	public class MfaController : Controller
	{
		private readonly ILogger logger;
		private readonly MyContext dbContext;
		private readonly IFido2 fido;

		private static readonly Dictionary<string, AssertionOptions> assertOptions = new Dictionary<string, AssertionOptions>();

		public MfaController(ILogger<MfaController> logger, MyContext dbContext, IFido2 fido)
		{
			this.logger = logger;
			this.dbContext = dbContext;
			this.fido = fido;
		}

		public IActionResult Index()
		{
			ViewData["Title"] = "Multi-Factor Authentication";
			var authUser = HttpContext.GetAuthUser();
			if (authUser == null)
				return Unauthorized();

			ViewData["Tab"] = "totp";
			return View(new MfaViewModel());
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Totp(MfaViewModel model, string returnUrl)
		{
			ViewData["Title"] = "Multi-Factor Authentication";
			var authUser = HttpContext.GetAuthUser(dbContext);
			if (authUser == null)
				return Unauthorized();

			ViewData["Tab"] = "totp";
			HttpContext.Items[HttpItem.RequestPath] = returnUrl;

			var totp = new Totp(Base32Encoding.ToBytes(authUser.TotpSecret));
			if (totp.VerifyTotp(model.TotpKey, out _))
			{
				await AccountController.SignIn(HttpContext, authUser, true);
				if (Url.IsLocalUrl(HttpContext.GetOriginalRequest()))
					return Redirect(HttpContext.GetOriginalRequest());

				return RedirectToAction("Index", "Home");
			}

			ModelState.AddModelError(nameof(model.TotpKey), "The code is invalid");
			return View("Index", model);
		}

		public IActionResult GetOptions()
		{
			var authUser = HttpContext.GetAuthUser();
			if (authUser == null)
				return Unauthorized();

			var existingCredentials = dbContext.WebAuthnKeys
				.Where(k => !k.IsLogin)
				.Where(k => k.UserId == authUser.Id)
				.Select(k => k.DescriptorJson)
				.AsEnumerable()
				.Select(d => JsonConvert.DeserializeObject<PublicKeyCredentialDescriptor>(d))
				.ToList();
			var extensions = new AuthenticationExtensionsClientInputs
			{
				SimpleTransactionAuthorization = "LoginExperiments WebAuthn",
				GenericTransactionAuthorization = new TxAuthGenericArg
				{
					ContentType = "text/plain",
					Content = Encoding.UTF8.GetBytes("FIDO2")
				},
				UserVerificationIndex = true,
				UserVerificationMethod = true,
				Location = true
			};

			var options = fido.GetAssertionOptions(existingCredentials, UserVerificationRequirement.Discouraged, extensions);
			string uid = Guid.NewGuid().ToString();
			assertOptions.Add(uid, options);

			if (options.RpId == "localhost")
				logger.LogWarning("WebAuthn Relaying Party ID is set to localhost - MFA may fail! Set correct ASPNETCORE_APPL_URL environment variable to fix this issue.");

			return Json(new JObject
			{
				["uid"] = uid,
				["options"] = JObject.FromObject(options)
			});
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> MakeAssert(string uid, string data)
		{
			var authUser = HttpContext.GetAuthUser();
			if (authUser == null)
				return Unauthorized();

			if (string.IsNullOrWhiteSpace(uid))
				return BadRequest("No UID");
			if (string.IsNullOrWhiteSpace(data))
				return BadRequest("No data received");

			var rawResponse = JsonConvert.DeserializeObject<AuthenticatorAssertionRawResponse>(data);
			assertOptions.Remove(uid, out var options);

			var credentials = dbContext.WebAuthnKeys
				.Where(k => k.UserId == authUser.Id)
				.Where(k => !k.IsLogin)
				.Where(k => k.DescriptorId == AccountController.ToHex(rawResponse.Id))
				.FirstOrDefault();
			if (credentials == null)
				return NotFound();

			async Task<bool> Callback(IsUserHandleOwnerOfCredentialIdParams args)
			{
				return await dbContext.WebAuthnKeys
					.Where(k => !k.IsLogin)
					.Where(k => k.UserId == AccountController.SafeInt(args.UserHandle))
					.Where(k => k.DescriptorId == AccountController.ToHex(args.CredentialId))
					.AnyAsync();
			};

			var counter = credentials.Counter;
			var res = await fido.MakeAssertionAsync(rawResponse, options, credentials.PublicKey, counter, Callback);
			credentials.Counter = counter;
			dbContext.SaveChanges();

			if (res.Status == "ok")
			{
				await AccountController.SignIn(HttpContext, authUser, true);
				return Ok();
			}
			return BadRequest();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Recovery(MfaViewModel model, string returnUrl)
		{
			ViewData["Title"] = "Multi-Factor Authentication";
			var authUser = HttpContext.GetAuthUser(dbContext);
			if (authUser == null)
				return Unauthorized();

			ViewData["Tab"] = "recovery";
			HttpContext.Items[HttpItem.RequestPath] = returnUrl;

			if (authUser.RecoveryKey == model.RecoveryKey)
			{
				await AccountController.SignIn(HttpContext, authUser, true);
				if (Url.IsLocalUrl(HttpContext.GetOriginalRequest()))
					return Redirect(HttpContext.GetOriginalRequest());

				return RedirectToAction("Index", "Home");
			}

			ModelState.AddModelError(nameof(model.RecoveryKey), "The recovery key is invalid");
			return View("Index", model);
		}
	}
}

LoginExperiments/Views/Mfa/Index.cshtml
@model MfaViewModel
@{
	var token = Context.GetAntiforgeryToken();
}

<h1 class="h1">Multi-Factor Authentication</h1>
<ul class="nav nav-pills nav-justified mb-4" role="tablist">
	<li class="nav-item" role="presentation">
		<a href="#totp" class="nav-link@(ViewBag.Tab == "totp" ? " active" : "")" id="totp-tab" data-toggle="tab" role="tab" aria-controls="totp">TOTP</a>
	</li>
	<li class="nav-item" role="presentation">
		<a href="#authn" class="nav-link@(ViewBag.Tab == "webauthn" ? " active" : "")" id="authn-tab" data-toggle="tab" role="tab" aria-controls="authn">FIDO2</a>
	</li>
	<li class="nav-item" role="presentation">
		<a href="#recovery" class="nav-link@(ViewBag.Tab == "recovery" ? " active" : "")" id="recovery-tab" data-toggle="tab" role="tab" aria-controls="recovery">Recovery Key</a>
	</li>
</ul>

<div class="tab-content">
	<div class="tab-pane fade@(ViewBag.Tab == "totp" ? " show active" : "")" id="totp" aria-labelledby="totp-tab">
		<p class="small text-muted">
			<strong>T</strong>ime-based <strong>O</strong>ne-<strong>T</strong>ime-<strong>P</strong>asswords are usually generated with an authenticator app (e.g. Authy or Microsoft Authenticator).
		</p>
		<form asp-controller="Mfa" asp-action="Totp" asp-route-returnUrl="@Context.GetOriginalRequest()" method="post">
			<div class="form-group">
				<label asp-for="TotpKey">Code</label>
				<input asp-for="TotpKey" class="form-control">
				<span asp-validation-for="TotpKey"></span>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-block">Submit</button>
			</div>
		</form>
	</div>
	<div class="tab-pane fade@(ViewBag.Tab == "webauthn" ? " show active" : "")" id="authn" aria-labelledby="authn-tab">
		<p class="small text-muted">
			With using FIDO2, the browser's native WebAuthn feature is used to authenticate the user.
		</p>
		<div class="form-group">
			<button type="button" class="btn btn-primary btn-block" id="webauthn">Authenticate</button>
		</div>
	</div>
	<div class="tab-pane fade@(ViewBag.Tab == "recovery" ? " show active" : "")" id="recovery" aria-labelledby="recovery-tab">
		<p class="small text-muted">
			The recovery key can be used whenever no other option is available (e.g. device is missing).
		</p>
		<form asp-controller="Mfa" asp-action="Recovery" asp-route-returnUrl="@Context.GetOriginalRequest()" method="post">
			<div class="form-group">
				<label asp-for="RecoveryKey">Recovery Key</label>
				<input asp-for="RecoveryKey" class="form-control">
				<span asp-validation-for="RecoveryKey"></span>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-block">Submit</button>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	<script type="text/javascript">
		$(function () {
			$('#webauthn').click(async event => {
				event.preventDefault();
				let response = await fetch('@Url.Action("GetOptions", "Mfa")');
				let json = await response.json();

				if (json.options.status !== 'ok') {
					console.error('WebAuthn options failed', json.options.errorMessage);
					alert('Could not load the needed parameters');
					return;
				}

				json.options.challenge = coerceToArrayBuffer(json.options.challenge);
				json.options.allowCredentials = json.options.allowCredentials.map(c => {
					c.id = coerceToArrayBuffer(c.id);
					return c;
				});

				let credential = await navigator.credentials.get({ publicKey: json.options });
				let cred = {
					id: credential.id,
					rawId: base64Encode(credential.rawId),
					type: credential.type,
					extensions: credential.getClientExtensionResults(),
					response: {
						authenticatorData: base64Encode(credential.response.authenticatorData),
						clientDataJSON: base64Encode(credential.response.clientDataJSON),
						signature: base64Encode(credential.response.signature),
						userHandle: null
					}
				};
				if (credential.response.userHandle !== null)
					cred.response.userHandle = base64Encode(credential.response.userHandle);

				let data = new FormData();
				data.append('uid', json.uid);
				data.append('data', JSON.stringify(cred));
				data.append('@token.Name', '@token.Value');

				response = await fetch('@Url.Action("MakeAssert", "Mfa")', {
					method: 'POST',
					body: data
				});

				if (response.ok)
					location.href = '@Context.GetOriginalRequest()';
			})
		});
	</script>
}